version: "3.9"
services:
  build-arch:
    platform: amd64
    network_mode: host
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/build/Dockerfile.arch
    volumes:
      - type: bind
        source: .
        target: /ctune
      - type: bind
        source: $XDG_RUNTIME_DIR/pulse
        target: $XDG_RUNTIME_DIR/pulse
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /etc/passwd
        target: /etc/passwd:ro
      - type: bind
        source: /etc/group
        target: /etc/group:ro
      - type: bind
        source: ./docker/out
        target: /output
    user: ${HOST_UID}:${HOST_GID}
    environment:
      - DISPLAY=unix$DISPLAY
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
      - XDG_DATA_HOME=/output
      - XDG_CONFIG_HOME=/output