#ifndef CTUNE_UI_ENUM_CONTEXTID_H
#define CTUNE_UI_ENUM_CONTEXTID_H

typedef enum ctune_UI_Context {
    CTUNE_UI_CTX_MAIN = 0,
    CTUNE_UI_CTX_FAV_TAB,
    CTUNE_UI_CTX_SEARCH_TAB,
    CTUNE_UI_CTX_BROWSE_TAB,
    CTUNE_UI_CTX_RSFIND,
    CTUNE_UI_CTX_RSINFO,
    CTUNE_UI_CTX_RSEDIT,
    CTUNE_UI_CTX_OPT_MENU,
    CTUNE_UI_CTX_SETOUTDIR,

    CTUNE_UI_CTX_COUNT,
} ctune_UI_Context_e;

#endif //CTUNE_UI_ENUM_CONTEXTID_H