#ifndef CTUNE_UI_ENUM_ICONID_H
#define CTUNE_UI_ENUM_ICONID_H

typedef enum ctune_UI_IconID {
    CTUNE_UI_ICON_UP_ARROW = 0,
    CTUNE_UI_ICON_DOWN_ARROW,
    CTUNE_UI_ICON_LEFT_ARROW,
    CTUNE_UI_ICON_RIGHT_ARROW,
    CTUNE_UI_ICON_STOPPED,
    CTUNE_UI_ICON_PLAYING,

    CTUNE_UI_ICON_COUNT,
} ctune_UI_IconID_e;

#endif //CTUNE_UI_ENUM_ICONID_H
