#ifndef CTUNE_UI_ENUM_ICONID_H
#define CTUNE_UI_ENUM_ICONID_H

typedef enum ctune_UI_IconID {
    CTUNE_UI_ICON_VOID       =  0,

    CTUNE_UI_ICON_VBAR_0_8TH =  1,
    CTUNE_UI_ICON_VBAR_1_8TH =  2,
    CTUNE_UI_ICON_VBAR_2_8TH =  3,
    CTUNE_UI_ICON_VBAR_3_8TH =  4,
    CTUNE_UI_ICON_VBAR_4_8TH =  5,
    CTUNE_UI_ICON_VBAR_5_8TH =  6,
    CTUNE_UI_ICON_VBAR_6_8TH =  7,
    CTUNE_UI_ICON_VBAR_7_8TH =  8,
    CTUNE_UI_ICON_VBAR_8_8TH =  9,

    CTUNE_UI_ICON_HBAR_0_8TH = 10,
    CTUNE_UI_ICON_HBAR_1_8TH = 11,
    CTUNE_UI_ICON_HBAR_2_8TH = 12,
    CTUNE_UI_ICON_HBAR_3_8TH = 13,
    CTUNE_UI_ICON_HBAR_4_8TH = 14,
    CTUNE_UI_ICON_HBAR_5_8TH = 15,
    CTUNE_UI_ICON_HBAR_6_8TH = 16,
    CTUNE_UI_ICON_HBAR_7_8TH = 17,
    CTUNE_UI_ICON_HBAR_8_8TH = 18,

    CTUNE_UI_ICON_SCROLL_UP,
    CTUNE_UI_ICON_SCROLL_DOWN,
    CTUNE_UI_ICON_SCROLL_LEFT,
    CTUNE_UI_ICON_SCROLL_RIGHT,
    CTUNE_UI_ICON_UP_ARROW,
    CTUNE_UI_ICON_DOWN_ARROW,
    CTUNE_UI_ICON_LEFT_ARROW,
    CTUNE_UI_ICON_RIGHT_ARROW,
    CTUNE_UI_ICON_STOPPED,
    CTUNE_UI_ICON_PLAYING,
    CTUNE_UI_ICON_WINCTRL_CLOSE,
    CTUNE_UI_ICON_VOLUME,

    CTUNE_UI_ICON_COUNT,
} ctune_UI_IconID_e;

#endif //CTUNE_UI_ENUM_ICONID_H
