#ifndef CTUNE_UI_ENUM_INPUTKEY_H
#define CTUNE_UI_ENUM_INPUTKEY_H

typedef enum ctune_UI_InputKey {
    CTUNE_UI_INPUTKEY_ERR = 0,
    CTUNE_UI_INPUTKEY_NONE,

    /* Keyboard input */
    CTUNE_UI_INPUTKEY_ESC,
    CTUNE_UI_INPUTKEY_F1,
    CTUNE_UI_INPUTKEY_F2,
    CTUNE_UI_INPUTKEY_F3,
    CTUNE_UI_INPUTKEY_F4,
    CTUNE_UI_INPUTKEY_F5,
    CTUNE_UI_INPUTKEY_F6,
    CTUNE_UI_INPUTKEY_F7,
    CTUNE_UI_INPUTKEY_F8,
    CTUNE_UI_INPUTKEY_F9,
    CTUNE_UI_INPUTKEY_F10,
    CTUNE_UI_INPUTKEY_F11,
    CTUNE_UI_INPUTKEY_F12,
    CTUNE_UI_INPUTKEY_RETURN,
    CTUNE_UI_INPUTKEY_TAB,
    CTUNE_UI_INPUTKEY_STAB,
    CTUNE_UI_INPUTKEY_BACKSPACE,
    CTUNE_UI_INPUTKEY_ALT_BACKSPACE,
    CTUNE_UI_INPUTKEY_SPACE,
    CTUNE_UI_INPUTKEY_DELCHAR,
    CTUNE_UI_INPUTKEY_SDELCHAR,
    CTUNE_UI_INPUTKEY_DELLINE,
    CTUNE_UI_INPUTKEY_SDELLINE,
    CTUNE_UI_INPUTKEY_INSLINE,
    CTUNE_UI_INPUTKEY_INSCHAR,
    CTUNE_UI_INPUTKEY_SINSCHAR,
    CTUNE_UI_INPUTKEY_HOME,
    CTUNE_UI_INPUTKEY_SHOME,
    CTUNE_UI_INPUTKEY_END,
    CTUNE_UI_INPUTKEY_HOMEDOWN,
    CTUNE_UI_INPUTKEY_UPPERLEFT,
    CTUNE_UI_INPUTKEY_UPPERRIGHT,
    CTUNE_UI_INPUTKEY_CENTER,
    CTUNE_UI_INPUTKEY_LOWERLEFT,
    CTUNE_UI_INPUTKEY_LOWERRIGHT,
    CTUNE_UI_INPUTKEY_PAGEUP,
    CTUNE_UI_INPUTKEY_PAGEDOWN,
    CTUNE_UI_INPUTKEY_UP,
    CTUNE_UI_INPUTKEY_DOWN,
    CTUNE_UI_INPUTKEY_LEFT,
    CTUNE_UI_INPUTKEY_RIGHT,
    CTUNE_UI_INPUTKEY_SLEFT,
    CTUNE_UI_INPUTKEY_SRIGHT,
    CTUNE_UI_INPUTKEY_NEXT,
    CTUNE_UI_INPUTKEY_PREVIOUS,
    CTUNE_UI_INPUTKEY_SNEXT,
    CTUNE_UI_INPUTKEY_SPREVIOUS,
    CTUNE_UI_INPUTKEY_EXIT,
    CTUNE_UI_INPUTKEY_SEXIT,
    CTUNE_UI_INPUTKEY_FIND,
    CTUNE_UI_INPUTKEY_SFIND,
    CTUNE_UI_INPUTKEY_HELP,
    CTUNE_UI_INPUTKEY_SHELP,
    CTUNE_UI_INPUTKEY_OPTIONS,
    CTUNE_UI_INPUTKEY_1,
    CTUNE_UI_INPUTKEY_2,
    CTUNE_UI_INPUTKEY_3,
    CTUNE_UI_INPUTKEY_4,
    CTUNE_UI_INPUTKEY_5,
    CTUNE_UI_INPUTKEY_6,
    CTUNE_UI_INPUTKEY_7,
    CTUNE_UI_INPUTKEY_8,
    CTUNE_UI_INPUTKEY_9,
    CTUNE_UI_INPUTKEY_0,
    CTUNE_UI_INPUTKEY_PLUS,
    CTUNE_UI_INPUTKEY_MINUS,
    CTUNE_UI_INPUTKEY_E,
    CTUNE_UI_INPUTKEY_F,
    CTUNE_UI_INPUTKEY_I,
    CTUNE_UI_INPUTKEY_N,
    CTUNE_UI_INPUTKEY_O,
    CTUNE_UI_INPUTKEY_P,
    CTUNE_UI_INPUTKEY_Q,
    CTUNE_UI_INPUTKEY_R,
    CTUNE_UI_INPUTKEY_S,
    CTUNE_UI_INPUTKEY_X,
    CTUNE_UI_INPUTKEY_CTRL_D,
    CTUNE_UI_INPUTKEY_CTRL_F,
    CTUNE_UI_INPUTKEY_CTRL_I,

    /* Event input */
    CTUNE_UI_INPUTKEY_MOUSE_EVENT,
    CTUNE_UI_INPUTKEY_RESIZE,

    CTUNE_UI_INPUTKEY_COUNT,
} ctune_UI_InputKey_e;

//KEY_STAB	/* set-tab key */
//KEY_CTAB	/* clear-tab key */
//KEY_CATAB	/* clear-all-tabs key */
//KEY_ENTER	/* enter/send key */
//KEY_PRINT	/* print key */
//KEY_BTAB	/* back-tab key */
//KEY_OPEN	/* open key */


#endif //CTUNE_UI_ENUM_INPUTKEY_H
