#ifndef CTUNE_ENUM_PLAYBACKCTRL_H
#define CTUNE_ENUM_PLAYBACKCTRL_H

enum CTUNE_PLAYBACK_CTRL {
    CTUNE_PLAYBACK_CTRL_STATE  = 0,
    CTUNE_PLAYBACK_CTRL_OFF    = 1,
    CTUNE_PLAYBACK_CTRL_ON     = 2,
    CTUNE_PLAYBACK_CTRL_SWITCH = 3
};

#endif //CTUNE_PLAYBACKCTRL_H
