#ifndef CTUNE_ENUM_SEARCHCTRL_H
#define CTUNE_ENUM_SEARCHCTRL_H

enum CTUNE_SEARCH_CTRL {
    CTUNE_SEARCH_CTRL_STATE = 0,
    CTUNE_SEARCH_CTRL_STOP  = 1,
    CTUNE_SEARCH_CTRL_START = 2,
};

#endif //CTUNE_ENUM_SEARCHCTRL_H