#ifndef CTUNE_CMAKE_CMAKE_VARS_H
#define CTUNE_CMAKE_CMAKE_VARS_H

#define CTUNE_APPNAME               "@PROJECT_NAME@"
#define CTUNE_AUTHOR                "@PROJECT_AUTHOR@"
#define CTUNE_YEARS                 "@PROJECT_YEARS@"
#define CTUNE_HOMEPAGE_URL          "@PROJECT_HOMEPAGE_URL@"
#define CTUNE_VERSION               "@PROJECT_VERSION@"
#define CTUNE_USERAGENT             "@PROJECT_NAME@/@PROJECT_VERSION@"
#define CTUNE_VERSION_MAJOR         @PROJECT_VERSION_MAJOR@
#define CTUNE_VERSION_MINOR         @PROJECT_VERSION_MINOR@
#define CTUNE_VERSION_PATCH         @PROJECT_VERSION_PATCH@
#define CTUNE_AUDIOOUT_INFO         "@CTUNE_AUDIOOUT_INFO@"
#define CTUNE_LICENSE               "AGPL3"
#define CTUNE_SYSLIB_PATH           "@CTUNE_INSTALL_LIBDIR@"
#define CTUNE_PLUGIN_PLAYER_DFLT    "@CTUNE_PLAYER_PLUGIN_DFLT@"
#define CTUNE_PLUGIN_SNDSRV_DFLT    "@CTUNE_OUTPUT_PLUGIN_DFLT@"

#endif //CTUNE_CMAKE_CMAKE_VARS_H