#ifndef CTUNE_AUDIO_CHANNEL_POSITION_H
#define CTUNE_AUDIO_CHANNEL_POSITION_H

//completely unused at the moment... left for potential future use

enum channel_position {
    CHANNEL_POSITION_INVALID = -1,

    CHANNEL_POSITION_MONO = 0,

    CHANNEL_POSITION_FRONT_LEFT,
    CHANNEL_POSITION_LEFT = CHANNEL_POSITION_FRONT_LEFT, //Apple & Dolby

    CHANNEL_POSITION_FRONT_RIGHT,
    CHANNEL_POSITION_RIGHT = CHANNEL_POSITION_FRONT_RIGHT, //Apple & Dolby

    CHANNEL_POSITION_FRONT_CENTER,
    CHANNEL_POSTION_CENTER = CHANNEL_POSITION_FRONT_CENTER, //Apple & Dolby

    CHANNEL_POSITION_REAR_CENTER,
    CHANNEL_POSITION_BACK_CENTER          = CHANNEL_POSITION_REAR_CENTER, //Microsoft
    CHANNEL_POSITION_CENTER_SURROUND      = CHANNEL_POSITION_REAR_CENTER, //Apple
    CHANNEL_POSITIOM_SURROUND_REAR_CENTER = CHANNEL_POSITION_REAR_CENTER, //Dolby

    CHANNEL_POSITION_REAR_LEFT,
    CHANNEL_POSITION_BACK_LEFT          = CHANNEL_POSITION_REAR_LEFT, //Microsoft
    CHANNEL_POSITION_LEFT_SURROUND      = CHANNEL_POSITION_REAR_LEFT, //Apple
    CHANNEL_POSITION_SURROUND_REAR_LEFT = CHANNEL_POSITION_REAR_LEFT, //Dolby

    CHANNEL_POSITION_REAR_RIGHT,
    CHANNEL_POSITION_BACK_RIGHT          = CHANNEL_POSITION_REAR_RIGHT, //Microsoft
    CHANNEL_POSITION_RIGHT_SURROUND      = CHANNEL_POSITION_REAR_RIGHT, //Apple
    CHANNEL_POSITION_SURROUND_REAR_RIGHT = CHANNEL_POSITION_REAR_RIGHT, //Dolby

    CHANNEL_POSITION_LFE,
    CHANNEL_POSITION_LOW_FREQ   = CHANNEL_POSITION_LFE, //Microsoft
    CHANNEL_POSITION_LFE_SCREEN = CHANNEL_POSITION_LFE, //Apple

    CHANNEL_POSITION_FRONT_LEFT_OF_CENTER,
    CHANNEL_POSITION_LEFT_CENTER = CHANNEL_POSITION_FRONT_LEFT_OF_CENTER, //Apple & Dolby

    CHANNEL_POSITION_FRONT_RIGHT_OF_CENTER,
    CHANNEL_POSITION_RIGHT_CENTER = CHANNEL_POSITION_FRONT_RIGHT_OF_CENTER, //Apple & Dolby

    CHANNEL_POSITION_SIDE_LEFT,
    CHANNEL_POSITION_LEFT_SURROUND_DIRECT = CHANNEL_POSITION_SIDE_LEFT, //Apple
    CHANNEL_POSITION_SURROUND_LEFT        = CHANNEL_POSITION_SIDE_LEFT, //Dolby

    
    CHANNEL_POSITION_SIDE_RIGHT,
    CHANNEL_POSITION_RIGHT_SURROUND_DIRECT = CHANNEL_POSITION_SIDE_RIGHT, //Apple
    CHANNEL_POSITION_SURROUND_RIGHT        = CHANNEL_POSITION_SIDE_RIGHT, //Dolby
    
    CHANNEL_POSITION_AUX0,
    CHANNEL_POSITION_AUX1,
    CHANNEL_POSITION_AUX2,
    CHANNEL_POSITION_AUX3,
    CHANNEL_POSITION_AUX4,
    CHANNEL_POSITION_AUX5,
    CHANNEL_POSITION_AUX6,
    CHANNEL_POSITION_AUX7,
    CHANNEL_POSITION_AUX8,
    CHANNEL_POSITION_AUX9,
    CHANNEL_POSITION_AUX10,
    CHANNEL_POSITION_AUX11,
    CHANNEL_POSITION_AUX12,
    CHANNEL_POSITION_AUX13,
    CHANNEL_POSITION_AUX14,
    CHANNEL_POSITION_AUX15,
    CHANNEL_POSITION_AUX16,
    CHANNEL_POSITION_AUX17,
    CHANNEL_POSITION_AUX18,
    CHANNEL_POSITION_AUX19,
    CHANNEL_POSITION_AUX20,
    CHANNEL_POSITION_AUX21,
    CHANNEL_POSITION_AUX22,
    CHANNEL_POSITION_AUX23,
    CHANNEL_POSITION_AUX24,
    CHANNEL_POSITION_AUX25,
    CHANNEL_POSITION_AUX26,
    CHANNEL_POSITION_AUX27,
    CHANNEL_POSITION_AUX28,
    CHANNEL_POSITION_AUX29,
    CHANNEL_POSITION_AUX30,
    CHANNEL_POSITION_AUX31,
    
    CHANNEL_POSITION_TOP_CENTER,
    CHANNEL_POSITION_TOP_CENTER_SURROUND = CHANNEL_POSITION_TOP_CENTER, //Apple
    
    CHANNEL_POSITION_TOP_FRONT_LEFT,
    CHANNEL_POSITION_VERTICAL_HEIGHT_LEFT = CHANNEL_POSITION_TOP_FRONT_LEFT, //Apple

    CHANNEL_POSITION_TOP_FRONT_RIGHT,
    CHANNEL_POSITION_VERTICAL_HEIGHT_RIGHT = CHANNEL_POSITION_TOP_FRONT_RIGHT, //Apple
    
    CHANNEL_POSITION_TOP_FRONT_CENTER,
    CHANNEL_POSITION_VERTICAL_HEIGHT_CENTER = CHANNEL_POSITION_TOP_FRONT_CENTER, //Apple
    
    CHANNEL_POSITION_TOP_REAR_LEFT,
    CHANNEL_POSITION_TOP_BACK_LEFT = CHANNEL_POSITION_TOP_REAR_LEFT, //Microsoft & Apple
    
    CHANNEL_POSITION_TOP_REAR_RIGHT,
    CHANNEL_POSITION_TOP_BACK_RIGHT = CHANNEL_POSITION_TOP_REAR_RIGHT, //Microsoft & Apple
    
    CHANNEL_POSITION_TOP_REAR_CENTER,
    CHANNEL_POSITION_TOP_BACK_CENTER = CHANNEL_POSITION_TOP_REAR_CENTER, //Microsoft & Apple

    CHANNEL_POSITION_MAX
};

typedef enum channel_position channel_position_t;

#endif //CTUNE_AUDIO_CHANNEL_POSITION_H
